CV_BANKAS_URL = "https://www.cvbankas.lt/?padalinys%5B%5D=76&keyw="
CV_LT_URL_START = "https://www.cv.lt"
CV_LT_URL_DEEPER = "/it-telekomunikaciju-darbai"
CV_MARKET_URL_START = "https://www.cvmarket.lt"
CV_MARKET_URL_DEEPER = "/darbo-skelbimai?op=search&search%5Bjob_salary%5D=3&ga_track=homepage&search%5Bcategories%5D%5B%5D=8&search%5Bkeyword%5D=&search%5Bexpires_days%5D=&search%5Bjob_lang%5D=&search%5Bsalary%5D="
CV_ONLINE_URL_START = "https://www.cvonline.lt"
CV_ONLINE_URL_DEEPER = "/lt/search?limit=20&offset=0&categories%5B0%5D=INFORMATION_TECHNOLOGY&fuzzy=true&suitableForRefugees=false&isHourlySalary=false&isRemoteWork=false&isQuickApply=false"
